# fly.toml app configuration file generated for fullstack-open-relational-databases-black-field-3790 on 2024-11-06T11:41:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-open-relational-databases-black-field-3790'
primary_region = 'qro'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
